### ISSUE TITLE
Cookie失效

### ISSUE THREAD

**Issue by yanzhonghui** [ruicky/jd_sign_bot#105]
一直失效，到底应该怎么弄。

**Comment by afderlqs** [comment]
参考：https://ruicky.me/2020/07/18/jd-cookie/

**Comment by admans** [comment]
我用楼上给的方法一直获取不到
用这个视频里的可以
https://www.bilibili.com/video/BV1si4y1M7GA?from=search&seid=13352110843952653612

**Comment by ruicky** [comment]
重新抓包 [参考](https://ruicky.me/2020/07/18/jd-cookie/)
