### ISSUE TITLE
Cookie失效

### ISSUE THREAD

**Issue by hugging-gff** [ruicky/jd_sign_bot#106]
老铁你们 需要更新代码了，一直提醒cookies 失效！！！！！！！！！！！！！！！！！！

**Comment by Echocruise** [comment]
京东的cookies本来就是一个月有效

**Comment by ruicky** [comment]
> 老铁你们 需要更新代码了，一直提醒cookies 失效！！！！！！！！！！！！！！！！！！

代码 只是 执行的框架， 你看下 你的 cookie 到底是否是对的
