### ISSUE TITLE
获取京东 cookie

### ISSUE THREAD

**Issue by 67snow** [ruicky/jd_sign_bot#108]
不使用文档中的方法。以下是我获取cookie的方法，亲测有效，不排除别的方法有效：电脑F12，H5登录京东，首页，Network，第一个请求中的，cookie

**Comment by smartqqh** [comment]
不好意思啊，能否解释一下Network第一个请求在哪里找到，谢谢

**Comment by smartqqh** [comment]
哦，不用了，刚看作者的博文https://ruicky.me/2020/07/18/jd-cookie/搞定了

**Comment by Y1988088888y** [comment]
帮我看看。我进了没?

**Comment by xb274271924** [comment]
666 之前一直是cookie失效。。这个方法起码第一次成功了，后面观察几天看看

**Comment by jbgsner** [comment]
这个方法成功了，谢谢

**Comment by behappy00** [comment]
> 这个方法成功了，谢谢

请问是哪个方法呢，我现在按照博主的方法 找不到 QueryUserInfoM ，求指教

**Comment by ruicky** [comment]
> > 这个方法成功了，谢谢
> 
> 请问是哪个方法呢，我现在按照博主的方法 找不到 QueryUserInfoM ，求指教

其实 不需要 额外 去找 这个url  ， 京东的一直在变， 你可以 看下 post 请求中的 header 中 一般的  cookie 就可以用的
