### ISSUE TITLE
自己调试自动执行，但是没有成功

### ISSUE THREAD

**Issue by lulingliangzai** [ruicky/jd_sign_bot#112]
大佬你好，我在yaml文件中将时间调整为  - cron: '50 13 * * *'  ，也就是我想调整为晚上9点50分自动执行，这是为了测试自动运行功能，但是到了时间点却没有执行，因为我没有收到sever酱的通知。请问这个是什么原因？

**Comment by ruicky** [comment]
cron: '50 13 * * *'  翻译过来是 13:50
你要是 晚上9点50  应该是 '50 21 * * *'

**Comment by lulingliangzai** [comment]
不是说有8个小时的时间差吗？
