### ISSUE TITLE
请问怎么修改执行时间啊?想改到8点执行

### ISSUE THREAD

**Issue by yujinxiangshala** [ruicky/jd_sign_bot#122]

**Comment by behappy00** [comment]
在 code 选项中有个 .github/workflows/work.yaml ，点击进去，最上面的
`on:
    push:
        branches:
            - master
    schedule:
        - cron: '5 16 * * *'
 `
其中 cron 就是你定义的执行时间，对应的是 UTC 时间 前面是分钟，后面是小时，想和北京时间转换的自己查一下

**Comment by ruicky** [comment]
Duplicate of #https://github.com/ruicky/jd_sign_bot/issues/140
