### ISSUE TITLE
凉凉了么-。-

### ISSUE THREAD

**Issue by renzhe1505** [ruicky/jd_sign_bot#148]
可以贡献下源码么 自己放在群晖里面整

**Comment by ccboxjole** [comment]
今天所有的签到脚本全部阵亡

**Comment by bao3** [comment]
> 今天所有的签到脚本全部阵亡

没有啊，我依然可以签到。没有任何变化，我刚刚看了看，成功 30/失败15 ，领取 32京豆

**Comment by renzhe1505** [comment]
> 今天所有的签到脚本全部阵亡

我阵亡几天了。。

**Comment by renzhe1505** [comment]
> > 今天所有的签到脚本全部阵亡
> 
> 没有啊，我依然可以签到。没有任何变化，我刚刚看了看，成功30 /失败15，领取32京豆

纳尼  我阵亡快一个星期了

**Comment by bao3** [comment]
京豆变动：
昨日 149京豆收入，总计1449 京豆。

脚本就是 repo 里引用的 NobyDa 原脚本

发自我的iPhone

**Comment by ruicky** [comment]
目前可以正常使用，挂的可以看下自己的cookie 是否正常。
