### ISSUE TITLE
add telegram api support

### ISSUE THREAD

**Issue by bao3** [ruicky/jd_sign_bot#149]
Reference:  [Wenmoux/V2ex-Auto-Sign](https://github.com/Wenmoux/V2ex-Auto-Sign/blob/master/v2ex.js)

Would you please add telegrambot support ? The benefit is telegram could show more detail message than Server Chan’s push notifies.

**Comment by ruicky** [comment]
好建议，后续可能会增加进去吧 只不过 目前由于网络问题，大路用 telegrambot 的少。
