### ISSUE TITLE
cookie没有生效

### ISSUE THREAD

**Issue by Guozisun** [ruicky/jd_sign_bot#17]
cookie没有生效
![Uploading image.png…]()

**Comment by Guozisun** [comment]
京东签到-9/22/2020
京东商城-京豆Cookie失效

京东商城-转盘查询成功

京东魔方-暂无有效活动

京东商城-摇一摇签到失败

京东商城-大奖查询KEY失败

京东现金-红包签到失败

京东商城-国际签到失败

**Comment by ruicky** [comment]
试试 重新获取一下。
