### ISSUE TITLE
签到的的时候提示需要验证才能拿京豆

### ISSUE THREAD

**Issue by LvDeShei** [ruicky/jd_sign_bot#192]
[签到的的时候提示需要验证才能拿京豆
![微信图片_20210323092739](https://user-images.githubusercontent.com/49177549/112078928-2a2ea080-8b77-11eb-875f-9bb1b69b40a9.jpg)

**Comment by mapeili521** [comment]
我也是，要滑动验证模块，才可以。

**Comment by LvDeShei** [comment]
嗯，只能手动来解决这个问题了，反正也不多，大约六七个。

**Comment by 2315247470** [comment]
就这？？ 不能自动跑 有啥用啊

**Comment by ruicky** [comment]
这个我没遇到过。我这个只是壳子，具体的实现在文章里都说明了。
