### ISSUE TITLE
没有出错，但京豆没有增长

### ISSUE THREAD

**Issue by dacs6** [ruicky/jd_sign_bot#2]
未配置推送，运行后无错误信息，但对比运行前后的京豆数量，没有增长。不知道如何进一步检查问题在哪里？
![20200808111650](https://user-images.githubusercontent.com/54759066/89701376-e466f400-d968-11ea-8967-e967bc901e78.png)

**Comment by ruicky** [comment]
先关闭，如果还有问题，请留言
