### ISSUE TITLE
全部失败，cookie没有生效

### ISSUE THREAD

**Issue by leonvogle** [ruicky/jd_sign_bot#20]
所有的都失败了，好像是cookie失效，不知道怎么回事，这是首次部署啊

**Comment by leonvogle** [comment]
我已经知道是怎么回事了，Cookie不需要全部内容，要筛选其中的内容，按照下面的格式写就行了
pt_key=xxx1;pt_pin=xxx1;

**Comment by happyzjhao** [comment]
可以了 谢谢

**Comment by ruicky** [comment]
没有具体的研究过 它要用哪些 cookie...

**Comment by X-Mars** [comment]
> 按照下面的格式写就行了

大佬  应该保留哪些 信息啊

**Comment by X-Mars** [comment]
https://www.bilibili.com/video/BV1si4y1M7GA?from=search&seid=13352110843952653612
手动复制cookies 后成功  感谢作者和楼主
