### ISSUE TITLE
再见

### ISSUE THREAD

**Issue by zhao141** [ruicky/jd_sign_bot#230]
有缘再见

**Comment by dyr9527** [comment]
感谢！有缘再见！

**Comment by silverstimes** [comment]
谢谢！有缘再见！

**Comment by bigdllmask1333** [comment]
再见，我这还有脚本，可以直接扫码挂机，需要的加wx，5元挂机1月，每天100-200京豆不等，微信概率获得红包0.32元，目前本人每天红包2-5个不等。这个看号，黑号别找我。挂机提前把京东里面所有的活动全部点开，什么汪汪宠物，摇钱树什么的。就是薅羊毛月入最低也有好几十了。 加wx发红包直接发二维码扫码上号 wx号:  cww0128

**Comment by zhao141** [comment]
> 再见，我这还有脚本，可以直接扫码挂机，需要的加wx，5元挂机1月，每天100-200京豆不等，微信概率获得红包0.32元，目前本人每天红包2-5个不等。这个看号，黑号别找我。挂机提前把京东里面所有的活动全部点开，什么汪汪宠物，摇钱树什么的。就是薅羊毛月入最低也有好几十了。 加wx发红包直接发二维码扫码上号 wx号: cww0128

你是不是找骂？在github上丢国人的脸

**Comment by ruicky** [comment]
切换分支有惊喜。
