### ISSUE TITLE
还想薅羊毛就点开

### ISSUE THREAD

**Issue by bigdllmask1333** [ruicky/jd_sign_bot#233]
再见，我这还有脚本，可以直接扫码挂机，需要的加wx，5元挂机1月，每天100-200京豆不等，微信概率获得红包0.32元，目前本人每天红包2-5个不等。这个看号，黑号别找我。挂机提前把京东里面所有的活动全部点开，什么汪汪宠物，摇钱树什么的。就是薅羊毛月入最低也有好几十了。 加wx发红包直接发二维码扫码上号 wx号: cww0128

**Comment by RomanticHW** [comment]
哎 就因为有你这样的人

**Comment by ruicky** [comment]
楼上的广告 大家不要轻易相信 避免上当受骗
