### ISSUE TITLE
脚本运行成功，但是所有签到都提示失败。

### ISSUE THREAD

**Issue by doeasier** [ruicky/jd_sign_bot#28]
脚本运行成功，但是所有签到都提示失败。失败原因：Cookie失效!!重取了两次cookie都没有用，但是网页里登录的帐户还是正常的，是怎么回事？

**Comment by Tyrone2333** [comment]
我也是这样,后面在手机浏览器用手机号登录,然后抓包拿 cookie 就可以了,试一下

**Comment by doeasier** [comment]
> 我也是这样,后面在手机浏览器用手机号登录,然后抓包拿 cookie 就可以了,试一下

我后来也是在手机上抓包拿到cookie后可以用，谢谢你的回复
