### ISSUE TITLE
如何添加京东第三方的店铺签到

### ISSUE THREAD

**Issue by tarianwei** [ruicky/jd_sign_bot#3]
比如飞利浦官方旗舰店的签到是下面的链接，抓包出来是这样的：https://lzkj-isv.isvjcloud.com/sign/signActivity2?activityId=c716918ff3e74b3e86154abc836aa364

谢谢

**Comment by xingluli** [comment]
兄dei，你搞定了吗？我也在看第三方怎么签到，第三方的发送请求返回的都是空

**Comment by tarianwei** [comment]
> 兄dei，你搞定了吗？我也在看第三方怎么签到，第三方的发送请求返回的都是空

没有搞定，我的返回值也是空的，可能是京东一定要求微信小程序操作，比如你在微信里打开上面的链接会提示你扫码使用小程序。所以代码模拟了手机操作时我们只是打开了链接，而不是打开的小程序

**Comment by xingluli** [comment]
但是在chrome打开链接，登陆后也是可以签到的。说明不一定非要小程序操作啊。我这边还有很多店铺可以测试，如果有兴趣的话加我TIM ，我发给你285943902

**Comment by tarianwei** [comment]
> 但是在chrome打开链接，登陆后也是可以签到的。说明不一定非要小程序操作啊。我这边还有很多店铺可以测试，如果有兴趣的话加我TIM ，我发给你285943902

是Sourire吧，QQ上加你了

**Comment by ruicky** [comment]
该签到机器人，调用的是别人实行代码，本工具，只是封装运行。
