### ISSUE TITLE
刚获取的cookie就提示失效

### ISSUE THREAD

**Issue by Liyooo** [ruicky/jd_sign_bot#59]
刚获取的cookie就提示失效是怎么回事。。连着重新登陆京东试了好几遍都不行。

**Comment by luodaozhang** [comment]
me toooo

**Comment by georgewu57** [comment]
chrome浏览器按F12登录，然后在网络里面找到名称为m.jd.com开头的项目，然后在标头栏找到cookie，复制后面的内容即可！

**Comment by e8732** [comment]
我也是

**Comment by ghc1996** [comment]
同问  这是什么情况 请问有人解决了吗

**Comment by ghc1996** [comment]
> 刚获取的cookie就提示失效是怎么回事。。连着重新登陆京东试了好几遍都不行。

请问问题解决了吗 同问

**Comment by Tyrone2333** [comment]
> > 刚获取的cookie就提示失效是怎么回事。。连着重新登陆京东试了好几遍都不行。
> 
> 请问问题解决了吗 同问

不要用 pc,用手机抓包获取 cookie

**Comment by ruicky** [comment]
> 刚获取的cookie就提示失效是怎么回事。。连着重新登陆京东试了好几遍都不行。

https://ruicky.me/2020/07/18/jd-cookie/
参考一下这篇

**Comment by happinesslijian** [comment]
chrome浏览器按F12登录，然后在Network里面找到名称为m.jd.com开头的项目，然后在标头栏找到cookie，复制后面的内容即可！


![微信截图_20201204143008](https://user-images.githubusercontent.com/47111417/101130325-3cbfb100-363e-11eb-9760-9eaacbf66a0e.png)

![微信截图_20201204143110](https://user-images.githubusercontent.com/47111417/101130338-41846500-363e-11eb-8950-328b90dbd942.png)
