### ISSUE TITLE
收到的推送消息持续报Cookie过期错误

### ISSUE THREAD

**Issue by Nutingnon** [ruicky/jd_sign_bot#79]
收到的推送消息持续报Cookie过期错误，用的是验证码登录的。已清除过cookie尝试，仍然报同样的错误

**Comment by lplbb** [comment]
我也是，请问解决了吗

**Comment by yanzhuan051** [comment]
> 收到的推送消息持续报Cookie过期错误，用的是验证码登录的。已清除过cookie尝试，仍然报同样的错误

一样的问题，验证码登陆 cooike 过期

**Comment by lplbb** [comment]
已解决，cookie过期，重新获取cookie，手机验证码登录一个月不失效

**Comment by ruicky** [comment]
一般都是 cookie 过期导致的。
填写cookie的时候 分辨一下 ，不要抓错了， 一般都是 GET 请求中 找 那个 最长 cookie的就是。
