### ISSUE TITLE
手机找不到这么多签到的入口，有谁知道么。

### ISSUE THREAD

**Issue by bbhxwl** [ruicky/jd_sign_bot#8]
手机找不到这么多签到的入口，有谁知道么。想自己做一个，只找到两三个签到的地方。。。用别人的cookie怕不放心。。

**Comment by xingluli** [comment]
你能找到第三方店铺的请求地址吗

**Comment by bbhxwl** [comment]
> 你能找到第三方店铺的请求地址吗

能在手机操作的，都可以代码模拟啊，不过我京东没找到这么多签到的入口呢。

**Comment by xingluli** [comment]
我找到了，但是发送请求时返回的数据不对，你要是有兴趣可以加我TIM，我发给你一些签到入口，你来试试285943902

**Comment by ruicky** [comment]
close
