### ISSUE TITLE
小白请教可以自定义运行时间吗?

### ISSUE THREAD

**Issue by shahid6** [ruicky/jd_sign_bot#87]
小白请教怎么修改执行的时间，比如定时早上8点。

**Comment by ruicky** [comment]
> 小白请教怎么修改执行的时间，比如定时早上8点。

可以是可以 但是需要修改 action 里的  yaml corn的时间， 但是不建议修改到8点。因为很多活动都是 凌晨的时候最多。如果8点执行的话 会损失很多豆豆的。

**Comment by a5234338** [comment]
@ruicky 我看yaml corn默认时间是下午4点，那是不是改到0点0分比较合理？
