### ISSUE TITLE
本项目对于京东活动还有上升空间

### ISSUE THREAD

**Issue by happinesslijian** [ruicky/jd_sign_bot#93]
下面的链接内有很多本项目里没有涉及到的京东活动 建议筛选合并到本项目中[jd_scripts](https://github.com/lxk0301/jd_scripts/tree/master)

**Comment by happinesslijian** [comment]
建议集成到本项目中
https://github.com/lxk0301/jd_scripts/tree/master#script%E8%84%9A%E6%9C%AC%E5%88%97%E8%A1%A8

**Comment by dcthedo** [comment]
确实希望能有更多活动脚本。。。。只不过也不过了这个

**Comment by happinesslijian** [comment]
nothing
