### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by Lunrry** [ruicky/jd_sign_bot#97]
执行时提示Cookie失效，但是我是手机登录后获取的cookie马上就提交的，请问是什么原因？

**Comment by ruicky** [comment]
> 执行时提示Cookie失效，但是我是手机登录后获取的cookie马上就提交的，请问是什么原因？

1. 登录最好使用验证码登录
2. 确认抓取cookie 是否正确，一般那个cookie 都是很长的

**Comment by chehongbin** [comment]
cookie 的格式是咋样的， 我只 存了pin 和 key
